name: tienda_login
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  http: any
  image_picker: ^0.8.0+3 
  get: ^4.6.1
  fl_chart: ^0.40.0
  page_transition: ^2.1.0
  table_calendar: ^3.0.9
  flutter_neat_and_clean_calendar: ^0.3.0+12
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^23.1.40
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^23.1.40
  flutter_svg_provider: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mkni.png.
    - assets/home.png.
    - assets/homesvg.svg.
    - assets/Mark.png.
    - assets/Mark1.png
    - assets/MarN.png






  fonts:
    - family: Open Sans
      fonts:
       - asset: assets/OpenSans-VariableFont_wdth,wght.ttf

    - family: Noto Sans
      fonts:
        - asset: assets/NotoSans-Bold.ttf # Asegúrate de que la ruta sea correcta
    
    - family: Bebas Neue
      fonts:
       - asset: assets/BebasNeue-Regular.ttf